version: '3'
services:
  database:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_DB=team_metrics_test
    expose:
      - "5432"
  app:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres@database:5432/team_metrics
    depends_on:
      - database
