"""empty message

Revision ID: 0001 Add team_metric table
Revises: 
Create Date: 2018-12-07 23:43:38.197548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001 Add team_metric table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_metric',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.DateTime(), nullable=False),
    sa.Column('ended_on', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cycle_time', sa.String(), nullable=False),
    sa.Column('process_cycle_efficiency', sa.Float(), nullable=False),
    sa.Column('num_completed', sa.Integer(), nullable=False),
    sa.Column('num_incomplete', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_metric')
    # ### end Alembic commands ###
