"""empty message

Revision ID: 0002 Add avg_cycle_time
Revises: 0001 Add team_metric table
Create Date: 2018-12-14 13:27:20.393726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002 Add avg_cycle_time'
down_revision = '0001 Add team_metric table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_metric', sa.Column('avg_cycle_time', sa.Integer(), nullable=False))
    op.drop_column('team_metric', 'cycle_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_metric', sa.Column('cycle_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team_metric', 'avg_cycle_time')
    # ### end Alembic commands ###
