"""empty message

Revision ID: 0002 change sprint_id to string
Revises: 0001 add team_metric
Create Date: 2019-01-03 13:39:57.149677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002 change sprint_id to string'
down_revision = '0001 add team_metric'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_metric', 'sprint_id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_metric', 'sprint_id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
