"""empty message

Revision ID: 0003 add git metrics
Revises: 0002 change sprint_id to string
Create Date: 2019-01-18 12:41:31.798007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003 add git metrics'
down_revision = '0002 change sprint_id to string'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_metric',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('diff_count', sa.Integer(), nullable=False),
    sa.Column('total_diff_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('team_id', 'repo_url', 'pr_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_metric')
    # ### end Alembic commands ###
