"""empty message

Revision ID: 0004 use repo name not url
Revises: 0003 add git metrics
Create Date: 2019-01-19 10:42:10.958121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004 use repo name not url'
down_revision = '0003 add git metrics'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_metric', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('git_metric', 'repo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_metric', sa.Column('repo_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('git_metric', 'name')
    # ### end Alembic commands ###
