---
resources:
- name: team-metrics-git
  type: git
  source:
    branch: master
    uri: https://github.com/alphagov/team-metrics.git
- name: deploy-to-paas
  type: cf
  source:
    api: https://api.cloud.service.gov.uk
    username: ((cloud_foundry_username))
    password: ((cloud_foundry_password))
    organization: gds-tech-ops
    space: traceability

jobs:
- name: test-and-build
  public: false
  plan:
    - get: team-metrics-git
      trigger: true
    - task: run-unit-tests
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: amidos/dcind
        inputs:
          - name: team-metrics-git
        run:
          path: sh
          args:
            - -exc
            - |
              source /docker-lib.sh
              start_docker

              cd team-metrics-git

              docker-compose build
              docker-compose up --abort-on-container-exit

    - task: build-assets
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: 10.13.0
        inputs:
          - name: team-metrics-git
        outputs:
          - name: team-metrics-git-built
        run:
          path: sh
          args:
            - -exc
            - |
              cp -r team-metrics-git/* team-metrics-git-built/
              cd team-metrics-git-built
              ./install-frontend-assets.sh
              npx webpack

    - put: deploy-to-paas
      params:
        manifest: team-metrics-git-built/manifest.yml
        show_app_log: true
        path: team-metrics-git-built
